const data = [
    {
       id:"1",
       name:"Krishna Veg",
       city:"6",
       area:"Nigdi",
       rating:"3.8",
       cloudinaryImageId:"z351qkt7qqjjxrrnocew",
       cuisines:["South Indian","North Indian","Chinese","Juices"],
       costForTwo:25000,
       costForTwoString:"₹250 For Two",
       deliveryTime:28,

    },
    {
        id:"2",
        name:"Savali",
        city:"7",
        area:"Nigdi",
        rating:"3.8",
        cloudinaryImageId:"lbye6vascq2ggicljkkw",
        cuisines:["South Indian","North Indian","Chinese","Juices"],
        costForTwo:3000,
        costForTwoString:"₹300 For Two",
        deliveryTime:17,
    },
   
    {
        id:"3",
        name:"Mazzedar",
        city:"7",
        area:"Nigdi",
        rating:"4.5",
        cloudinaryImageId:"hmrj06hczmliwslhlgja",
        cuisines:["Biryani","North Indian","Chinese","Beverages"],
        costForTwo:5500,
        costForTwoString:"₹250 For Two",
        deliveryTime:27,
    },
    {
        id:"4",
        name:"Geeta Pav Bhaji",
        city:"7",
        area:"Nigdi",
        rating:"4.2",
        cloudinaryImageId:"mhkg6xxwxqrzrz7qj6mx",
        cuisines:["South Indian","Ice-cream","Juices"],
        costForTwo:1000,
        costForTwoString:"₹370 For Two",
        deliveryTime:15,
    },
    {
        id:"5",
        name:"Deli Belly",
        city:"9",
        area:"Nigdi",
        rating:"3.1",
        cloudinaryImageId:"2cab3b337584d36c974daa2c4bec1f2a",
        cuisines:["North Indian","Chinese","Beverages"],
        costForTwo:2700,
        costForTwoString:"₹399 For Two",
        deliveryTime:12,
    },
    {
        id:"6",
        name:"Krishna Veg Treat",
        city:"7",
        area:"Nigdi",
        rating:"4.8",
        cloudinaryImageId:"bxxfr0v1f0pjwfcxhwub",
        cuisines:["South Indian","Maharashtrian","Chinese","Juices"],
        costForTwo:3000,
        costForTwoString:"₹300 For Two",
        deliveryTime:17,
    },
    {
        id:"7",
        name:"Burgerino",
        city:"7",
        area:"Nigdi",
        rating:"4.9",
        cloudinaryImageId:"512de94363c22a9db4d8beb84268716f",
        cuisines:["South Indian","Maharashtrian","Chinese","Juices"],
        costForTwo:2500,
        costForTwoString:"₹200 For Two",
        deliveryTime:17,
    }
]
export default data;